### ISSUE TITLE
unsafe_free () from /run/opengl-driver/lib/dri/nouveau_dri.so

### ISSUE THREAD

**Issue by nixinator** [rombust/Methane#2]
everything is working well, however on exit i get a segfault :-(. It's probably my broken operating system, or my old broken nvidia card drivers.

Here's a couple of backtraces. however it's no biggie... I can live with it.

```
Thread 1 "methane" received signal SIGSEGV, Segmentation fault.
0x00007fffed64157d in unsafe_free () from /run/opengl-driver/lib/dri/nouveau_dri.so
(gdb) backtrace
#0  0x00007fffed64157d in unsafe_free () from /run/opengl-driver/lib/dri/nouveau_dri.so
#1  0x00007fffed64158a in unsafe_free () from /run/opengl-driver/lib/dri/nouveau_dri.so
#2  0x00007fffed58050c in _mesa_glsl_builtin_functions_decref () from /run/opengl-driver/lib/dri/nouveau_dri.so
#3  0x00007fffed358155 in _mesa_free_context_data () from /run/opengl-driver/lib/dri/nouveau_dri.so
#4  0x00007fffed2cc077 in st_destroy_context () from /run/opengl-driver/lib/dri/nouveau_dri.so
#5  0x00007fffed2a9f2e in dri_destroy_context () from /run/opengl-driver/lib/dri/nouveau_dri.so
#6  0x00007fffed7f6163 in driDestroyContext () from /run/opengl-driver/lib/dri/nouveau_dri.so
#7  0x00007fffeea6b32f in dri3_destroy_context () from /run/opengl-driver/lib/libGLX_mesa.so.0
#8  0x00007fffeea5a039 in glx_display_free () from /run/opengl-driver/lib/libGLX_mesa.so.0
#9  0x00007fffeea5a0cf in __glXCloseDisplay () from /run/opengl-driver/lib/libGLX_mesa.so.0
#10 0x00007ffff7bebbe2 in XCloseDisplay ()
   from /nix/store/80p7f1sw4szy7w1mhqxd268n6i1gmybs-libX11-1.7.0/lib/libX11.so.6
#11 0x00007ffff7e45970 in clan::DisplayMessageQueue_X11::~DisplayMessageQueue_X11() ()
   from /nix/store/j3c22q4y3jbiz9j3fbmg8nd9jnwbnvdx-clanlib-4.1.0/lib/libclan41Display-4.1.so.1
#12 0x00007ffff7dfb429 in clan::SetupDisplay_Impl::~SetupDisplay_Impl() ()
   from /nix/store/j3c22q4y3jbiz9j3fbmg8nd9jnwbnvdx-clanlib-4.1.0/lib/libclan41Display-4.1.so.1
#13 0x00007ffff7dfb479 in clan::SetupDisplay_Impl::~SetupDisplay_Impl() ()
   from /nix/store/j3c22q4y3jbiz9j3fbmg8nd9jnwbnvdx-clanlib-4.1.0/lib/libclan41Display-4.1.so.1
#14 0x00007ffff78bc9ef in clan::SetupCore::~SetupCore() ()
   from /nix/store/j3c22q4y3jbiz9j3fbmg8nd9jnwbnvdx-clanlib-4.1.0/lib/libclan41Core-4.1.so.1
#15 0x00007ffff731cbf6 in __cxa_finalize ()
   from /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/libc.so.6
#16 0x00007ffff78b9273 in __do_global_dtors_aux ()
   from /nix/store/j3c22q4y3jbiz9j3fbmg8nd9jnwbnvdx-clanlib-4.1.0/lib/libclan41Core-4.1.so.1
#17 0x00007ffffffec660 in ?? ()
#18 0x00007ffff7fe1d47 in _dl_fini ()
   from /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/ld-linux-x86-64.so.2
```

```
Thread 3 "methane" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 24132]
0x00007ffff7384548 in __memset_sse2_unaligned_erms ()
   from /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff7384548 in __memset_sse2_unaligned_erms ()
   from /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/libc.so.6
#1  0x00007ffff7820f8d in VC1_WriteSamples ()
   from /nix/store/kpm7m57b3xhdgsyll1vgfifvp6s0y7p5-libmikmod-3.3.11.1/lib/libmikmod.so.3
#2  0x00007ffff7821ec6 in VC1_WriteBytes ()
   from /nix/store/kpm7m57b3xhdgsyll1vgfifvp6s0y7p5-libmikmod-3.3.11.1/lib/libmikmod.so.3
#3  0x0000000000425ddf in SoundProvider_MikMod_Session::get_data(float**, int) ()
#4  0x00007ffff7aa7f1c in clan::SoundBuffer_Session_Impl::get_data() ()
   from /nix/store/j3c22q4y3jbiz9j3fbmg8nd9jnwbnvdx-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1
#5  0x00007ffff7aa81b9 in clan::SoundBuffer_Session_Impl::get_data_in_mixer_frequency(int, float**) ()
   from /nix/store/j3c22q4y3jbiz9j3fbmg8nd9jnwbnvdx-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1
#6  0x00007ffff7aa83ba in clan::SoundBuffer_Session_Impl::mix_to(float**, float**, int, int) ()
   from /nix/store/j3c22q4y3jbiz9j3fbmg8nd9jnwbnvdx-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1
#7  0x00007ffff7aa5847 in clan::SoundOutput_Impl::fill_mix_buffers() ()
   from /nix/store/j3c22q4y3jbiz9j3fbmg8nd9jnwbnvdx-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1
#8  0x00007ffff7aa59b9 in clan::SoundOutput_Impl::mix_fragment() ()
   from /nix/store/j3c22q4y3jbiz9j3fbmg8nd9jnwbnvdx-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1
#9  0x00007ffff7aa5a18 in clan::SoundOutput_Impl::mixer_thread() ()
   from /nix/store/j3c22q4y3jbiz9j3fbmg8nd9jnwbnvdx-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1
#10 0x00007ffff76f5c50 in ?? () from /nix/store/z5l2fm9byiz5yr82iznkv2rynr85ajnv-gcc-10.2.0-lib/lib/libstdc++.so.6
#11 0x00007ffff74a7e9e in start_thread ()
   from /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/libpthread.so.0
#12 0x00007ffff73d949f in clone () from /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/libc.so.6
```

**Comment by rombust** [comment]
I can replicate the sound seg fault bug that occurs in about 1 in 10 exits of the program on my Linux Mint. I have implemented a fix, that apparently fixes it on mine.

I have not looked at the nouveau seg fault bug. I cannot replicate it at the moment, since I am using the Nividia official driver on Linux, instead of the open source one.

Also I have fixed a keyboard input bug I noticed today. See https://github.com/rombust/Methane/releases/tag/v2.0.1

Thanks for your help.

**Comment by nixinator** [comment]
I'll try out the new version, I ran it through valgrind too, but that thing tends to gives false positives sometimes.. so it's hard to say. I'll try the new version :-)

**Comment by nixinator** [comment]
I seem to have it failing in the same on exit in valgrind.

could be in libmikmod, or clanlib, hard to tell, and i maybe reading the trace wrong. However here is it for you.
could point to a null pointer defef.... ==3732==  Access not within mapped region at address 0x0   :-( 

```
==3732== 
==3732== Thread 3:
==3732== Invalid write of size 8
==3732==    at 0x483F406: memset (in /nix/store/b87y9fv4c1jwq9zmrqr3kbhyyfj9xp1h-valgrind-3.16.1/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3732==    by 0x5005F8C: VC1_WriteSamples (in /nix/store/kpm7m57b3xhdgsyll1vgfifvp6s0y7p5-libmikmod-3.3.11.1/lib/libmikmod.so.3.3.0)
==3732==    by 0x5006EC5: VC1_WriteBytes (in /nix/store/kpm7m57b3xhdgsyll1vgfifvp6s0y7p5-libmikmod-3.3.11.1/lib/libmikmod.so.3.3.0)
==3732==    by 0x426E0F: SoundProvider_MikMod_Session::get_data(float**, int) (soundprovider_mikmod_session.cpp:104)
==3732==    by 0x4D83F1B: clan::SoundBuffer_Session_Impl::get_data() (in /nix/store/npws6asazdhs61k62qxazn2vz1wvd3yz-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1.0.0)
==3732==    by 0x4D841B8: clan::SoundBuffer_Session_Impl::get_data_in_mixer_frequency(int, float**) (in /nix/store/npws6asazdhs61k62qxazn2vz1wvd3yz-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1.0.0)
==3732==    by 0x4D843B9: clan::SoundBuffer_Session_Impl::mix_to(float**, float**, int, int) (in /nix/store/npws6asazdhs61k62qxazn2vz1wvd3yz-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1.0.0)
==3732==    by 0x4D81846: clan::SoundOutput_Impl::fill_mix_buffers() (in /nix/store/npws6asazdhs61k62qxazn2vz1wvd3yz-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1.0.0)
==3732==    by 0x4D819B8: clan::SoundOutput_Impl::mix_fragment() (in /nix/store/npws6asazdhs61k62qxazn2vz1wvd3yz-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1.0.0)
==3732==    by 0x4D81A17: clan::SoundOutput_Impl::mixer_thread() (in /nix/store/npws6asazdhs61k62qxazn2vz1wvd3yz-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1.0.0)
==3732==    by 0x50F4C4F: ??? (in /nix/store/z5l2fm9byiz5yr82iznkv2rynr85ajnv-gcc-10.2.0-lib/lib/libstdc++.so.6.0.28)
==3732==    by 0x535AE9D: start_thread (in /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/libpthread-2.32.so)
==3732==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==3732== 
==3732== 
==3732== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==3732==  Access not within mapped region at address 0x0
==3732==    at 0x483F406: memset (in /nix/store/b87y9fv4c1jwq9zmrqr3kbhyyfj9xp1h-valgrind-3.16.1/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3732==    by 0x5005F8C: VC1_WriteSamples (in /nix/store/kpm7m57b3xhdgsyll1vgfifvp6s0y7p5-libmikmod-3.3.11.1/lib/libmikmod.so.3.3.0)
==3732==    by 0x5006EC5: VC1_WriteBytes (in /nix/store/kpm7m57b3xhdgsyll1vgfifvp6s0y7p5-libmikmod-3.3.11.1/lib/libmikmod.so.3.3.0)
==3732==    by 0x426E0F: SoundProvider_MikMod_Session::get_data(float**, int) (soundprovider_mikmod_session.cpp:104)
==3732==    by 0x4D83F1B: clan::SoundBuffer_Session_Impl::get_data() (in /nix/store/npws6asazdhs61k62qxazn2vz1wvd3yz-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1.0.0)
==3732==    by 0x4D841B8: clan::SoundBuffer_Session_Impl::get_data_in_mixer_frequency(int, float**) (in /nix/store/npws6asazdhs61k62qxazn2vz1wvd3yz-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1.0.0)
==3732==    by 0x4D843B9: clan::SoundBuffer_Session_Impl::mix_to(float**, float**, int, int) (in /nix/store/npws6asazdhs61k62qxazn2vz1wvd3yz-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1.0.0)
==3732==    by 0x4D81846: clan::SoundOutput_Impl::fill_mix_buffers() (in /nix/store/npws6asazdhs61k62qxazn2vz1wvd3yz-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1.0.0)
==3732==    by 0x4D819B8: clan::SoundOutput_Impl::mix_fragment() (in /nix/store/npws6asazdhs61k62qxazn2vz1wvd3yz-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1.0.0)
==3732==    by 0x4D81A17: clan::SoundOutput_Impl::mixer_thread() (in /nix/store/npws6asazdhs61k62qxazn2vz1wvd3yz-clanlib-4.1.0/lib/libclan41Sound-4.1.so.1.0.0)
==3732==    by 0x50F4C4F: ??? (in /nix/store/z5l2fm9byiz5yr82iznkv2rynr85ajnv-gcc-10.2.0-lib/lib/libstdc++.so.6.0.28)
==3732==    by 0x535AE9D: start_thread (in /nix/store/hp8wcylqr14hrrpqap4wdrwzq092wfln-glibc-2.32-37/lib/libpthread-2.32.so)
==3732==  If you believe this happened as a result of a stack
==3732==  overflow in your program's main thread (unlikely but
==3732==  possible), you can try to increase the size of the
==3732==  main thread stack using the --main-stacksize= flag.
==3732==  The main thread stack size used in this run was 16777216.
==3732== 
==3732== HEAP SUMMARY:
==3732==     in use at exit: 7,361,606 bytes in 52,533 blocks
==3732==   total heap usage: 132,052 allocs, 79,519 frees, 52,791,885 bytes allocated
==3732== 
==3732== LEAK SUMMARY:
==3732==    definitely lost: 149,237 bytes in 23 blocks
==3732==    indirectly lost: 39 bytes in 2 blocks
==3732==      possibly lost: 5,026,550 bytes in 37,742 blocks
==3732==    still reachable: 2,185,780 bytes in 14,766 blocks
==3732==         suppressed: 0 bytes in 0 blocks
==3732== Rerun with --leak-check=full to see details of leaked memory
==3732== 
==3732== Use --track-origins=yes to see where uninitialised values come from
==3732== For lists of detected and suppressed errors, rerun with: -s
==3732== ERROR SUMMARY: 8 errors from 3 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

**Comment by rombust** [comment]
This should have been fixed August last year. It was a bug in ClanLib.    Thank you for reporting. I forgot to mention it here.
